export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const REFRESH_INGREDIENTS = 'REFRESH_INGREDIENTS';
export const ADD_AMOUNT = 'ADD_AMOUNT';
export const SUBTRACT_AMOUNT = 'SUBTRACT_AMOUNT';